BEGIN;

CREATE TABLE IF NOT EXISTS app_clients (
    id BIGSERIAL PRIMARY KEY,
    browser_id TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT app_clients_browser_id_not_blank
        CHECK (LENGTH(BTRIM(browser_id)) > 0)
);

ALTER TABLE app_clients
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE app_clients
    ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

COMMIT;
